version: '3.7'
services:
  app:
    build: .
    volumes:
      - /node_modules
    ports:
      - "3003:3003"
    environment:
      MONGODB_URI: mongodb://mongo:27017/nest
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
